package model;
// Generated 3 mars 2015 12:14:20 by Hibernate Tools 3.6.0


import contrat.Metier;
import java.util.HashSet;
import java.util.Set;

/**
 * CategorieProduit generated by hbm2java
 */
public class CategorieProduit extends Metier  implements java.io.Serializable {


     private int idCategorieProduit;
     private String libelle;


    public CategorieProduit() {
    }

	
    public CategorieProduit(int idCategorieProduit) {
        this.idCategorieProduit = idCategorieProduit;
    }
    
    public CategorieProduit(int idCategorieProduit, String libelle) {
       this.idCategorieProduit = idCategorieProduit;
       this.libelle = libelle;

    }
   
    public int getIdCategorieProduit() {
        return this.idCategorieProduit;
    }
    
    public void setIdCategorieProduit(int idCategorieProduit) {
        this.idCategorieProduit = idCategorieProduit;
    }
    
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }


}


