package model;
// Generated 3 mars 2015 12:14:20 by Hibernate Tools 3.6.0


import contrat.Metier;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande extends Metier implements java.io.Serializable {


     private int idCommande;
     private Fournisseur fournisseur;
     private Personnel personnel;
     private Client client;
     private String designation;
     private Boolean typeCommande;
     private Boolean paiement;
     private Date dateCommande;
     private String tauxTva;
     private Set factures = new HashSet(0);
     private Set produits = new HashSet(0);

    public Commande() {
    }

	
    public Commande(int idCommande, Fournisseur fournisseur, Personnel personnel, Client client) {
        this.idCommande = idCommande;
        this.fournisseur = fournisseur;
        this.personnel = personnel;
        this.client = client;
    }
    public Commande(int idCommande, Fournisseur fournisseur, Personnel personnel, Client client, String designation, Boolean typeCommande, Boolean paiement, Date dateCommande, String tauxTva, Set factures, Set produits) {
       this.idCommande = idCommande;
       this.fournisseur = fournisseur;
       this.personnel = personnel;
       this.client = client;
       this.designation = designation;
       this.typeCommande = typeCommande;
       this.paiement = paiement;
       this.dateCommande = dateCommande;
       this.tauxTva = tauxTva;
       this.factures = factures;
       this.produits = produits;
    }
   
    public int getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Boolean getTypeCommande() {
        return this.typeCommande;
    }
    
    public void setTypeCommande(Boolean typeCommande) {
        this.typeCommande = typeCommande;
    }
    public Boolean getPaiement() {
        return this.paiement;
    }
    
    public void setPaiement(Boolean paiement) {
        this.paiement = paiement;
    }
    public Date getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(Date dateCommande) {
        this.dateCommande = dateCommande;
    }
    public String getTauxTva() {
        return this.tauxTva;
    }
    
    public void setTauxTva(String tauxTva) {
        this.tauxTva = tauxTva;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }

    public Set getProduits() {
        return produits;
    }

    public void setProduits(Set produits) {
        this.produits = produits;
    }
  
    




}


