package model;
// Generated 3 mars 2015 12:14:20 by Hibernate Tools 3.6.0


import contrat.Metier;
import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur extends Metier  implements java.io.Serializable {


     private int idFournisseur;
     private String raisonSocial;


    public Fournisseur() {
    }

	
    public Fournisseur(int idFournisseur) {
        this.idFournisseur = idFournisseur;
    }
    public Fournisseur(int idFournisseur, String raisonSocial, Set commandes, Set produits) {
       this.idFournisseur = idFournisseur;
       this.raisonSocial = raisonSocial;

    }
   
    public int getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(int idFournisseur) {
        this.idFournisseur = idFournisseur;
    }
    public String getRaisonSocial() {
        return this.raisonSocial;
    }
    
    public void setRaisonSocial(String raisonSocial) {
        this.raisonSocial = raisonSocial;
    }





}


