package model;
// Generated 3 mars 2015 12:14:20 by Hibernate Tools 3.6.0


import contrat.Metier;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel extends Metier  implements java.io.Serializable {


     private int idPersonnel;
     private String nom;
     private String prenom;
     private String password;
     private String matricule;
     private String service;
     private Set commandes = new HashSet(0);

    public Personnel() {
    }

	
    public Personnel(int idPersonnel, String password) {
        this.idPersonnel = idPersonnel;
        this.password = password;
    }
    public Personnel(int idPersonnel, String nom, String prenom, String password, String matricule, String service, Set commandes) {
       this.idPersonnel = idPersonnel;
       this.nom = nom;
       this.prenom = prenom;
       this.password = password;
       this.matricule = matricule;
       this.service = service;
       this.commandes = commandes;
    }
   
    public int getIdPersonnel() {
        return this.idPersonnel;
    }
    
    public void setIdPersonnel(int idPersonnel) {
        this.idPersonnel = idPersonnel;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


