package model;
// Generated 3 mars 2015 12:14:20 by Hibernate Tools 3.6.0


import contrat.Metier;
import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit extends Metier  implements java.io.Serializable {


     private int idProduit;
     private Fournisseur fournisseur;
     private CategorieProduit categorieProduit;
     private String libelle;
     private String prixAchat;
     private String prixVente;
     private String refProduit;
     private int stockMin;
     private int stockMax;
     private int stock;
   

    public Produit() {
    }

	
    public Produit(int idProduit, Fournisseur fournisseur, CategorieProduit categorieProduit) {
        this.idProduit = idProduit;
        this.fournisseur = fournisseur;
        this.categorieProduit = categorieProduit;
    }

    public Produit(int idProduit, Fournisseur fournisseur, CategorieProduit categorieProduit, String libelle, String prixAchat, String prixVente, String refProduit, int stockMin, int stockMax, int stock) {
        this.idProduit = idProduit;
        this.fournisseur = fournisseur;
        this.categorieProduit = categorieProduit;
        this.libelle = libelle;
        this.prixAchat = prixAchat;
        this.prixVente = prixVente;
        this.refProduit = refProduit;
        this.stockMin = stockMin;
        this.stockMax = stockMax;
        this.stock = stock;
    }

   
    public int getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(int idProduit) {
        this.idProduit = idProduit;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    
    public CategorieProduit getCategorieProduit() {
        return this.categorieProduit;
    }
    
    public void setCategorieProduit(CategorieProduit categorieProduit) {
        this.categorieProduit = categorieProduit;
    }
    
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getPrixAchat() {
        return this.prixAchat;
    }
    
    public void setPrixAchat(String prixAchat) {
        this.prixAchat = prixAchat;
    }
    public String getPrixVente() {
        return this.prixVente;
    }
    
    public void setPrixVente(String prixVente) {
        this.prixVente = prixVente;
    }
    public String getRefProduit() {
        return this.refProduit;
    }
    
    public void setRefProduit(String refProduit) {
        this.refProduit = refProduit;
    }

    public int getStockMin() {
        return stockMin;
    }

    public void setStockMin(int stockMin) {
        this.stockMin = stockMin;
    }

    public int getStockMax() {
        return stockMax;
    }

    public void setStockMax(int stockMax) {
        this.stockMax = stockMax;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    
    
}


